language: php
sudo: false

matrix:
  include:
    - php: 5.6
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install

script:
  - composer phplint
  - composer phpcs
